CC=g++
CFLAGS=-W -Wall -c -ggdb 

all: 	amort_house amort_compare_house_flat

amort_house:			amort_house.o
amort_compare_house_flat:	amort_compare_house_flat.o

clean:
	rm -f 	amort_house amort_house.o amort_compare_house_flat amort_compare_house_flat.o \
